### ISSUE TITLE
Bootstrap and Font Awesome examples broken?

### ISSUE THREAD

**Issue by neokoenig** [blueriver/MuraBootstrap4Bundle#1]
Trying to access `http://localhost:62286/index.cfm/bootstrap/` for demo of Bootstrap elements results in:
```
Bootstrap Elements 
500 Error
Page /muraWRM/themes/default/display_objects/examples/bootstrapThemeExample.cfm [D:\muratest\themes\default\display_objects\examples\bootstrapThemeExample.cfm] not found
Code: 0
Type: 0
```
Same for the font awesome demo page.

Core Version 7.1.116 
App Server Lucee (5.2.4.37) 
DB Server MySQL (5.6.26-log)
Java Version 1.8.0_60
OS Version Windows 10 (10.0)

**Comment by stevewithington** [comment]
@neokoenig thanks for catching this. we've removed reference to those files.
